# Generated by Django 3.2 on 2023-07-31 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230727_1701'),
        ('users', '0004_user_password'),
    ]

    operations = [
    ]
