# Generated by Django 3.2 on 2023-08-02 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_password'),
        ('users', '0007_auto_20230802_1405'),
    ]

    operations = [
    ]
