# Generated by Django 4.0 on 2023-08-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=2),
        ),
    ]
